### PR TITLE
Great idea to consolidate binds and really make Quaggles' injector shine!

### PR DESCRIPTION
**Pull request by ReardonMetal27**
I added a few that I've been using. Probably have some more and will definitely be making more now that it's easy to re-enable them after updates.

I added a category to all of mine, "Custom Binds", just so they're easy to find. Similar to Heatblur's "Special for Joystick".

I was thinking it would be a cool way for new users to easily see all of the stuff this package adds.

Let me know if you have any conventions you'd like me to follow.

Later,
Tim

### CODE REVIEW

**Comment by ReardonMetal27** [comment]
Oh, also, I've used Git and BitBucket for some smaller personal projects but this is literally my first contribution to somebody else's...so let me know if I did it right or if there's anything I can do better. Don't be shy.

**Comment by Munkwolf** [comment]
Thanks for the contribution!

I've been on the fence with the custom binds category vs standardized approach. I like keeping it all grouped by instrument/location/standardized, but I know lots of other people prefer having all the custom stuff grouped.

I'm thinking of creating a new main folder, like InputCommands_Custom, and that can be a version with all the keybinds assigned to a 'Custom' category? Either way I'll be throwing together some scripts soon to help manage this stuff, and audit where gaps are.

Also, to your also, all good. I've handled lots of code stuff for work over the years, but never anything public, so similar situation where this is new to me in a lot of ways.  Everything in the pull looked good. In next day or two I'll cut/tag a release branch and (finally) update the readme a little more.

**Comment by ReardonMetal27** [comment]
Sweet!

Glad to hear a "Custom Binds" or similar category was already on your
radar. I also like having the binds show up in the same place as similar
stock binds (usually the bind I modified to make the custom). I've got good
news then, no need for a seperate main folder. Binds can be a member of
multiple categories, and many of the defaults already are. I kept the
default categories so the new binds will show up "next to" the similar
stock binds but *also* appear in a new category called "Custom Binds" so
that users can select that and quickly see all the new stuff available
after installation.

Here's an example from the F-16 binds I added:
[image: image.png]

So that will show up under the stock categories "Instrument Panel" and
"FLCS" just like the existing Autopilot binds, but also under a new
category "Custom Binds". It might be cool to call it "Community Keybinds
Project" or something like that to really call it out.

**Comment by Munkwolf** [comment]
I think that would be the best route. I was concerned about cluttering up each way by including both, but really doesn't seem to be any downside. It's more options, the custom ones will be in one group, and I doubt any fans of the Custom route will mind seeing the binds also available in the stock groupings.

Does the multiple category thing work for every module? I feel like I tried that on one a couple of weeks back and it didn't work so I held off. Thinking of Harrier, MiG-19, or MiG-21. Maybe I borked the syntax and didn't realize it.

Currently working on a node script to audit the clickabledata files vs the stock joystick/keyboard default.lua files vs what we have going here. End goal being an HTML report for the readme showing % coverage for each module and a list of what's added/missing. Just finished getting all the files wrangled into an object - now on to some regex to parse it all out by device and command for the comparison part..

**Pull request merged**
